### ISSUE TITLE
Search by contact name / phone number

### ISSUE THREAD

**Issue by EdmundMai** [RBCA/blue-collar#32]
![bcl_latest_sketch](https://user-images.githubusercontent.com/1857068/36999535-67bcfb42-208e-11e8-91cf-a2645df574c4.png)

**Comment by AaronVasquez** [comment]
@kru sorry, we might not be building this screen like this. Hope you didn't do too much already.

**Comment by kru** [comment]
Its okay, not started yet. My plan was to start it today.
