### ISSUE TITLE
Static header

### ISSUE THREAD

**Issue by EdmundMai** [RBCA/blue-collar#40]
![bcl_latest_sketch.png](https://images.zenhubusercontent.com/5a8c54174b5806bc2bc7ac4b/84db6567-6cbd-4a75-b941-d428ce9bc898)

**Comment by AaronVasquez** [comment]
Hold off on this screen. I'm asking Griff if we can use the native share extensions https://facebook.github.io/react-native/docs/share.html

**Comment by kru** [comment]
Noted.
